db:
  image: postgres:9.4
  ports:
    - "5432:5432"
  volumes:
    - ./docker/db/create_databases.sh:/docker-entrypoint-initdb.d/create_databases.sh
app:
  build: .
  env_file:
    - .envrc
  links:
    - db
